# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('suggest_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
    ]
