# Generated by Django 4.1 on 2022-08-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0003_alter_command_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the command can actually be used and is shown on the home page.'),
        ),
        migrations.AlterField(
            model_name='command',
            name='default',
            field=models.BooleanField(default=False, help_text="When true, this command is used if an incoming request doesn't match any command."),
        ),
        migrations.AlterField(
            model_name='command',
            name='description',
            field=models.TextField(blank=True, help_text='Currently unused.'),
        ),
        migrations.AlterField(
            model_name='command',
            name='keyword',
            field=models.CharField(help_text='This is the keyword that starts a command.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='suggest_url',
            field=models.URLField(blank=True, help_text='URL for suggesting completions. Not sure this even works anymore...'),
        ),
        migrations.AlterField(
            model_name='command',
            name='title',
            field=models.CharField(help_text='Displayed on the home page to identify/explain the command.', max_length=32),
        ),
        migrations.AlterField(
            model_name='command',
            name='url',
            field=models.URLField(help_text='The command is redirected to this URL. <code>%s</code> in the URL is replaced with the command argument.'),
        ),
        migrations.AlterField(
            model_name='command',
            name='use_count',
            field=models.IntegerField(default=0, help_text='How often this command was invoked. Used to style the home page.'),
        ),
    ]
