# Generated by Django 4.1 on 2022-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0004_alter_command_active_alter_command_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='description',
        ),
        migrations.AddField(
            model_name='command',
            name='empty_url',
            field=models.URLField(blank=True, help_text='If specified, this URL is used when the command is invoked without arguments.'),
        ),
    ]
