# Generated by Django 4.1 on 2022-08-09 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0005_remove_command_description_command_empty_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
