# Generated by Django 4.1 on 2022-08-09 14:44

from django.db import migrations


DEFAULT_COMMANDS = [
	('ls', False, 'Display webCLI commands', '/'),
	('g', True, 'Google Search', 'https://www.google.com/search?q=%s'),
	('gim', False, 'Google Image Search', 'https://images.google.com/images?q=%s'),
	('wp', False, 'Wikipedia search', 'https://en.wikipedia.org/?search=%s'),
	('tiny', False, 'Tinify a URL', 'https://tinyurl.com/create.php?url=%s'),
	('archive', False, 'Internet Archive lookup', 'https://web.archive.org/web/*/%s'),
]


def add_default_commands(apps, schema_editor):
	Command = apps.get_model('cli', 'Command')
	for (keyword, default, title, url) in DEFAULT_COMMANDS:
		if not Command.objects.filter(keyword=keyword).exists():
			Command(keyword=keyword, default=default, title=title, url=url).save()


class Migration(migrations.Migration):

	dependencies = [
		('cli', '0006_alter_command_created_at'),
	]

	operations = [
		migrations.RunPython(add_default_commands, migrations.RunPython.noop),
	]
