# Generated by Django 5.1 on 2024-08-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0008_alter_command_url_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='empty_url',
        ),
    ]
