# Generated by Django 5.1 on 2024-08-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0009_remove_command_empty_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='suggest_url',
        ),
    ]
